### ISSUE TITLE
Problem with stats

### ISSUE THREAD

**Issue by jlareos** [tijmenvandenbrink/enviroplus_exporter#16]
Hi!
First of all thank you for all this project. It's amazing.
I'm using your grafana dashboard and i'm getting this errors. Do you know how to fix it?
![stats](https://user-images.githubusercontent.com/19354278/122938605-30e5d300-d373-11eb-8d77-a7c5ebd18cd3.PNG)

**Comment by tijmenvandenbrink** [comment]
Hi @jlareos, perhaps you're using an older version of Grafana?

**Comment by jlareos** [comment]
Yep, that was the problem
