### ISSUE TITLE
Compensate temperature

### ISSUE THREAD

**Issue by jlareos** [tijmenvandenbrink/enviroplus_exporter#17]
Hi! is there anyway to compensate the temperature manually?
I bought a heat dissipator but even so the temperature increases 10C

**Comment by 46bit** [comment]
There's a `--factor` command line argument that you can use to try and compensate.

**Comment by vgnmnky** [comment]
How do you apply that --factor argument please?

**Comment by mabio91** [comment]
Hi! I'm trying to figure out how to compensate the temperature... I'm not able to find where is the factor value in the config file...

**Comment by tijmenvandenbrink** [comment]
Hi, you can provide an extra parameter to the startup command. See ./contrib/enviroplus-exporter.service.

Cheers
