### ISSUE TITLE
RFE -- support for EnviroPhat? 

### ISSUE THREAD

**Issue by brauhausdc** [tijmenvandenbrink/enviroplus_exporter#19]
Any chance you can add an option to support the EnviroPhat board? Yes, old, crusty and deprecated, but there's a few still out there.

**Comment by tijmenvandenbrink** [comment]
Sorry for not getting back to you earlier. I don't have the PHAT myself so it would be hard to introduce and support this. Thanks for your interest though.

Cheers,

Tijmen
