### ISSUE TITLE
combine this with script that uploads data to sensor.community from original enviro plus library

### ISSUE THREAD

**Issue by nookontherim** [tijmenvandenbrink/enviroplus_exporter#27]
would it be possible to run this program but also have the data uploaded to sensor.community at the same time, as the basic enviro-plus library does/is built to do? I imagine the answer is "yes of course its possible". but as a programming noob, I guess the more appropriate question would be would it be really difficult to make it do that? And if I wanted to try to take that project on, might you have any tips on how to do it?

**Comment by vgnmnky** [comment]
@nookontherim , did you manage to get it working?  I've had it working with the usual luftdaten script before, but not got it working through enviroplus_exporter so far.

**Comment by iancattermole** [comment]
Hi Guys, 

I too would love an answer on this one
I’ve managed to sort the temperature issue by adding a “factor” of 1.75 which kind of works

Sending data to luftdaten is my issue, no matter what I try
If I “sudo systemctl stop enviroplus-exporter”
I can then run 
enviroplus-python/examples/luftdaten.py & 
balena-environ-plus/luftdaten/ luftdaten.py
both working fine and sending data

Within enviroplus_exporter.py I’ve also tried changing 
'https://api.luftdaten.info/v1/push-sensor-data/',
to "https://api.sensor.community/v1/push-sensor-data/",

I’ve also tried to create a script to stop the server, send data to luftdaten.py, kill the connection then restart the server
Tried running both together – it doesn’t work
If anyone has the answer I would be grateful as I’ve spent way too much time on this
Such a project, just need the last bit to work

Thanks, Ian

**Comment by tijmenvandenbrink** [comment]
Just verified this works as expected (sending the stats to sensor.community and exposing the prometheus endpoint. Closing this issue.
